apiVersion: apps/v1
kind: Deployment

metadata:
  name: jenkins

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins

  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
